version: "2"

run:
  timeout: 30m
  modules-download-mode: readonly

linters:
  exclusions:
    paths:
      - cover
      - fix42
      - fix44
      - enum
      - enum/
      - ./enum
      - field
    rules:
      - linters:
          - errcheck
        text: " is not check"
  settings:
    dupl:
      threshold: 400
  disable:
    - staticcheck
  enable:
    - copyloopvar
    - dupl
    - govet
    - ineffassign
    - misspell
    - unused
    # - staticcheck
    - godot
    # - revive

formatters:
  exclusions:
    paths:
      - cover
      - fix42
      - fix44
      - enum
      - enum/
      - ./enum
      - field
  settings:
    gofmt:
      simplify: true
  enable:
    - goimports
    - gofmt
