name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  golangci:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    timeout-minutes: 30
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2 # v2.10.0
        with:
          golangci_lint_version: v2.8.0

  build:
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 30
    name: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: ['~1.25.0', '~1.26.0']
        fix-version:
          - ''
          - fix42
          - fix44
    steps:
      - name: Check out source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go }}
      - name: Install ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: '3.0'

      - name: mod download
        run: go mod download

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
        with:
          mongodb-replica-set: replicaset

      - name: Test
        env:
          GO111MODULE: on
          MONGODB_TEST_CXN: mongodb://localhost:27017
          FIX_TEST: ${{ matrix.fix-version }}
        run: if [ -z $FIX_TEST ]; then make build-src && make test-ci; else make generate-ci && make build && make $FIX_TEST; fi
